import StyledComponentsRegistry from '@/lib/AntdRegistry';
import './globals.css';
import './antd.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Roboto_Mono } from 'next/font/google';
import Providers from '@/redux/provider';
import { ConfigProvider } from 'antd';
import theme from '@/config/theme/themeConfig';
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const roboto = Roboto_Mono({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${roboto.variable} ${inter.variable} `}>
        <Providers>
          <StyledComponentsRegistry>
            <ConfigProvider theme={theme}>{children}</ConfigProvider>
          </StyledComponentsRegistry>
        </Providers>
      </body>
    </html>
  );
}
